import{NtfySignaling,createSessionSecret,normalizeSessionInput,sessionLabel}from"./signaling.js";
import{PeerSession}from"./peer.js";
import{TransferManager}from"./transfer.js";
const $=id=>document.getElementById(id);
const ui={home:$("home-view"),workspace:$("workspace-view"),status:$("global-status"),create:$("create-room-btn"),joinToggle:$("join-toggle-btn"),joinForm:$("join-form"),joinInput:$("join-input"),role:$("room-role"),title:$("room-title"),detail:$("room-detail"),shareActions:$("share-actions"),share:$("share-btn"),copy:$("copy-btn"),code:$("session-code"),peerOrb:$("peer-orb"),peerState:$("peer-state"),peerDetail:$("peer-detail"),path:$("path-badge"),transferArea:$("transfer-area"),dropZone:$("drop-zone"),fileInput:$("file-input"),transferCard:$("transfer-card"),transferName:$("transfer-name"),transferMeta:$("transfer-meta"),transferState:$("transfer-state"),progressBar:$("progress-bar"),progressText:$("progress-text"),speedText:$("speed-text"),transferActions:$("transfer-actions"),incoming:$("incoming-card"),incomingName:$("incoming-name"),incomingMeta:$("incoming-meta"),accept:$("accept-file-btn"),reject:$("reject-file-btn"),signalingState:$("signaling-state"),rtcState:$("rtc-state"),channelState:$("channel-state"),sinkState:$("sink-state"),debug:$("debug-log"),leave:$("leave-btn"),installBanner:$("install-banner"),installBtn:$("install-btn"),installCopy:$("install-copy"),installDismiss:$("install-dismiss")};
let signaling=null,peer=null,transfers=null,secret="",role="",shareUrl="",pendingIncoming=null,currentDownloadCleanup=null,deferredInstallPrompt=null;
function log(message){const time=new Date().toLocaleTimeString([],{hour12:false});ui.debug.textContent+="["+time+"] "+message+"\n";ui.debug.scrollTop=ui.debug.scrollHeight}
function humanSize(bytes){const units=["B","KB","MB","GB","TB"];let value=bytes,i=0;while(value>=1024&&i<units.length-1){value/=1024;i++}const display=value>=100?value.toFixed(0):value>=10?value.toFixed(1):value.toFixed(2);return display+" "+units[i]}
function setWorkspace(){ui.home.classList.add("hidden");ui.workspace.classList.remove("hidden")}
function resetProgress(){ui.progressBar.style.width="0%";ui.progressText.textContent="0%";ui.speedText.textContent="—";ui.transferActions.innerHTML=""}
function showTransfer(meta,state){ui.transferCard.classList.remove("hidden");ui.transferName.textContent=meta.name;ui.transferMeta.textContent=humanSize(meta.size);ui.transferState.textContent=state;resetProgress()}
function updateProgress(detail){const pct=detail.total?Math.min(100,detail.loaded/detail.total*100):0;ui.progressBar.style.width=pct+"%";ui.progressText.textContent=pct.toFixed(pct<10?1:0)+"% · "+humanSize(detail.loaded)+" / "+humanSize(detail.total);ui.speedText.textContent=detail.rate;ui.transferState.textContent=detail.direction==="send"?"Sending":"Receiving"}
function addCancelButton(){ui.transferActions.innerHTML="";const button=document.createElement("button");button.className="ghost-button";button.textContent="Cancel";button.onclick=()=>transfers?.cancelActive();ui.transferActions.append(button)}
async function beginSession(nextRole,nextSecret){
  role=nextRole;secret=nextSecret;setWorkspace();ui.status.textContent="signaling";ui.role.textContent=role==="host"?"SENDER ROOM":"JOINING ROOM";ui.title.textContent=role==="host"?"Waiting for another device":"Joining private session";ui.detail.textContent=role==="host"?"Share this link. The file itself never goes through the signaling service.":"Authenticating the room and negotiating WebRTC.";ui.shareActions.classList.toggle("hidden",role!=="host");shareUrl=location.origin+location.pathname+"#join/"+secret;ui.code.textContent=await sessionLabel(secret);
  signaling=new NtfySignaling(secret);signaling.addEventListener("state",event=>{ui.signalingState.textContent=event.detail;log("signaling: "+event.detail)});
  try{
    await signaling.connect();log("signaling transport connected");peer=new PeerSession(signaling,role);
    peer.addEventListener("state",async event=>{const state=event.detail;ui.rtcState.textContent=state;log("webrtc: "+state);if(state==="connected"){ui.peerOrb.className="peer-orb online";ui.peerState.textContent="Peer connected";ui.peerDetail.textContent="Encrypted WebRTC connection established";ui.status.textContent="connected";setTimeout(async()=>{ui.path.textContent=await peer.connectionPath()},800)}if(["failed","disconnected","closed"].includes(state))ui.peerOrb.className="peer-orb error"});
    peer.addEventListener("channel",event=>{const channel=event.detail;ui.channelState.textContent="open";ui.transferArea.classList.remove("hidden");ui.peerState.textContent="Ready to transfer";ui.peerDetail.textContent="Choose a file on either device";transfers=new TransferManager(channel,peer.safeChunkSize());bindTransfers();log("data channel open · chunk "+peer.safeChunkSize()+" bytes")});
    peer.addEventListener("channel-close",()=>{ui.channelState.textContent="closed";log("data channel closed")});
    peer.addEventListener("error",event=>{log("peer error: "+event.detail.message);ui.peerState.textContent="Connection error";ui.peerOrb.className="peer-orb error"});
    await peer.announce();if(role==="guest")log("join announcement sent")
  }catch(error){log("startup error: "+error.message);ui.status.textContent="error";ui.peerState.textContent="Could not start session";ui.peerDetail.textContent=error.message;ui.peerOrb.className="peer-orb error"}
}
function bindTransfers(){
  transfers.addEventListener("incoming",event=>{pendingIncoming=event.detail.meta;ui.incoming.classList.remove("hidden");ui.incomingName.textContent=pendingIncoming.name;ui.incomingMeta.textContent=humanSize(pendingIncoming.size)+" · "+(pendingIncoming.type||"unknown type");log("incoming offer: "+pendingIncoming.name+" ("+pendingIncoming.size+" bytes)")});
  transfers.addEventListener("offered",event=>{showTransfer(event.detail.meta,"Waiting for acceptance");addCancelButton();log("file offered: "+event.detail.meta.name)});
  transfers.addEventListener("sink",event=>{ui.sinkState.textContent=event.detail.kind;log("receive sink: "+event.detail.kind)});
  transfers.addEventListener("progress",event=>updateProgress(event.detail));
  transfers.addEventListener("rejected",event=>{ui.transferState.textContent="Declined";ui.transferActions.innerHTML="";log("file rejected: "+event.detail.reason)});
  transfers.addEventListener("cancelled",()=>{ui.transferState.textContent="Cancelled";ui.transferActions.innerHTML="";ui.incoming.classList.add("hidden");log("transfer cancelled")});
  transfers.addEventListener("error",event=>{ui.transferState.textContent="Error";ui.transferActions.innerHTML="";log("transfer error: "+event.detail.error.message)});
  transfers.addEventListener("complete",event=>{const direction=event.detail.direction,meta=event.detail.meta,result=event.detail.result;ui.transferState.textContent="Complete";ui.progressBar.style.width="100%";ui.progressText.textContent="100% · "+humanSize(meta.size);ui.transferActions.innerHTML="";if(direction==="receive"&&result?.blob){currentDownloadCleanup?.();const url=URL.createObjectURL(result.blob),link=document.createElement("a");link.className="small-button";link.textContent="Save file";link.download=meta.name;link.href=url;ui.transferActions.append(link);currentDownloadCleanup=async()=>{URL.revokeObjectURL(url);await result.cleanup?.()};log("receive complete via "+result.kind)}else log("send complete")})
}
async function sendFile(file){if(!transfers||!file)return;try{showTransfer({name:file.name,size:file.size},"Offering");const meta=transfers.offer(file);showTransfer(meta,"Waiting for acceptance");addCancelButton()}catch(error){log("send error: "+error.message)}}
ui.create.addEventListener("click",()=>beginSession("host",createSessionSecret()));
ui.joinToggle.addEventListener("click",()=>{ui.joinForm.classList.toggle("hidden");if(!ui.joinForm.classList.contains("hidden"))ui.joinInput.focus()});
ui.joinForm.addEventListener("submit",event=>{event.preventDefault();const nextSecret=normalizeSessionInput(ui.joinInput.value);if(nextSecret.length<16){ui.joinInput.setCustomValidity("Paste a valid shotbylove room link or session key.");ui.joinInput.reportValidity();return}ui.joinInput.setCustomValidity("");history.replaceState(null,"","#join/"+nextSecret);beginSession("guest",nextSecret)});
ui.share.addEventListener("click",async()=>{if(navigator.share){try{await navigator.share({title:"shotbylove transfer",text:"Join my private file transfer",url:shareUrl});return}catch{}}await navigator.clipboard.writeText(shareUrl);ui.share.textContent="Copied";setTimeout(()=>ui.share.textContent="Share link",1200)});
ui.copy.addEventListener("click",async()=>{await navigator.clipboard.writeText(shareUrl);ui.copy.textContent="Copied";setTimeout(()=>ui.copy.textContent="Copy",1200)});
ui.fileInput.addEventListener("change",()=>sendFile(ui.fileInput.files?.[0]));
for(const type of["dragenter","dragover"])ui.dropZone.addEventListener(type,event=>{event.preventDefault();ui.dropZone.classList.add("drag")});
for(const type of["dragleave","drop"])ui.dropZone.addEventListener(type,event=>{event.preventDefault();ui.dropZone.classList.remove("drag")});
ui.dropZone.addEventListener("drop",event=>sendFile(event.dataTransfer?.files?.[0]));
ui.accept.addEventListener("click",async()=>{if(!pendingIncoming)return;try{showTransfer(pendingIncoming,"Preparing storage");addCancelButton();ui.incoming.classList.add("hidden");await transfers.acceptIncoming();pendingIncoming=null}catch(error){ui.transferState.textContent="Cannot receive";log("receive setup error: "+error.message)}});
ui.reject.addEventListener("click",()=>{transfers?.rejectIncoming();pendingIncoming=null;ui.incoming.classList.add("hidden")});
ui.leave.addEventListener("click",()=>{signaling?.close();peer?.close();location.href=location.pathname});
window.addEventListener("beforeunload",()=>{currentDownloadCleanup?.();signaling?.close();peer?.close()});
window.addEventListener("beforeinstallprompt",event=>{event.preventDefault();deferredInstallPrompt=event;ui.installBanner.classList.remove("hidden")});
ui.installBtn.addEventListener("click",async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;ui.installBanner.classList.add("hidden")}});
ui.installDismiss.addEventListener("click",()=>ui.installBanner.classList.add("hidden"));
function maybeShowIosInstallHint(){const ios=/iPad|iPhone|iPod/.test(navigator.userAgent),standalone=navigator.standalone===true||matchMedia("(display-mode: standalone)").matches;if(ios&&!standalone&&!sessionStorage.getItem("sbl-install-dismissed")){ui.installCopy.textContent="Safari Share → Add to Home Screen";ui.installBtn.classList.add("hidden");ui.installBanner.classList.remove("hidden");ui.installDismiss.onclick=()=>{sessionStorage.setItem("sbl-install-dismissed","1");ui.installBanner.classList.add("hidden")}}}
async function registerServiceWorker(){if(!("serviceWorker"in navigator))return;try{const registration=await navigator.serviceWorker.register("./sw.js",{updateViaCache:"none"});registration.update().catch(()=>{})}catch(error){log("service worker: "+error.message)}}
registerServiceWorker();maybeShowIosInstallHint();const hashSecret=normalizeSessionInput(location.hash);if(hashSecret.length>=16){ui.joinForm.classList.remove("hidden");ui.joinInput.value=hashSecret;ui.joinInput.focus()}
